import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "../../styles/Home.module.css";
import name from "../../composants/composants1"

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className={styles.description}>
          <div className={styles.margin}>
            <h2 className={styles.blue}>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut nec consequat velit. Sed egestas mattis enim ut laoreet. Nulla eu mauris suscipit, condimentum sem sit amet, scelerisque ante. Nam in nulla nibh. Aliquam commodo mauris nec augue volutpat auctor. Nunc eu iaculis lacus, eu auctor libero. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Quisque ut consectetur risus, at dictum purus. Maecenas efficitur mi massa, quis cursus est consequat vitae. Aenean vestibulum, mi a fermentum pulvinar, sem nisi elementum quam, ac tempor lacus ex sit amet velit. Praesent consectetur dui leo, quis porta est vulputate blandit. Vestibulum scelerisque augue eu tellus feugiat, eget ultrices lectus porta. Sed quam velit, eleifend a quam hendrerit, egestas pharetra velit.
            </h2>
          </div>
        </div>
    </>
  );
}
